#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""旧 shared.configs 互換レイヤ。"""

from backend.settings import (
    GS_DEFAULT_PRESET,
    PDF_ALLOWED_MODES,
    PDF_LOSSLESS_OPTIONS_DEFAULT,
    PDF_LOSSY_DPI_DEFAULT,
    PDF_LOSSY_JPEG_QUALITY_DEFAULT,
    PDF_LOSSY_PNG_TO_JPEG_DEFAULT,
)
from frontend.settings import (
    APP_DEFAULT_INPUT_DIR,
    APP_DEFAULT_OUTPUT_DIR,
    APP_DEFAULT_WINDOW_SIZE,
    COPY_NON_TARGET_FILES_DEFAULT,
    DEBUG_MODE_DEFAULT,
    GS_PRESETS,
    IMAGES_DIR,
    INPUT_DIR_CLEANUP_EXTENSIONS,
    LONG_EDGE_PRESETS,
    OUTPUT_DIR_CLEANUP_EXTENSIONS,
    PDF_COMPRESS_MODES,
    PDF_LOSSY_DPI_RANGE,
    SOUNDS_DIR,
)
from shared.runtime_paths import APP_BASE_DIR, RESOURCE_BASE_DIR

__all__ = [
    'APP_BASE_DIR',
    'RESOURCE_BASE_DIR',
    'APP_DEFAULT_INPUT_DIR',
    'APP_DEFAULT_OUTPUT_DIR',
    'APP_DEFAULT_WINDOW_SIZE',
    'SOUNDS_DIR',
    'IMAGES_DIR',
    'INPUT_DIR_CLEANUP_EXTENSIONS',
    'OUTPUT_DIR_CLEANUP_EXTENSIONS',
    'PDF_COMPRESS_MODES',
    'PDF_ALLOWED_MODES',
    'PDF_LOSSY_DPI_RANGE',
    'PDF_LOSSY_DPI_DEFAULT',
    'PDF_LOSSY_JPEG_QUALITY_DEFAULT',
    'PDF_LOSSY_PNG_TO_JPEG_DEFAULT',
    'PDF_LOSSLESS_OPTIONS_DEFAULT',
    'GS_PRESETS',
    'GS_DEFAULT_PRESET',
    'LONG_EDGE_PRESETS',
    'DEBUG_MODE_DEFAULT',
    'COPY_NON_TARGET_FILES_DEFAULT',
]
